# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Deployment
        run: |
          curl -X POST -H "Authorization: token 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" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/code/deployments \
               -d '{
                 "ref": "main",
                 "task": "deploy",
                 "auto_merge": false,
                 "required_contexts": [],
                 "environment": "production",
                 "description": "Deploying latest version"
               }'
